/*******************************************************************************/
/*  This file is auto-generated by GUIX Studio. Do not edit this file by hand. */
/*  Modifications to this file should only be made by running the GUIX Studio  */
/*  application and re-generating the application resource file(s). For more   */
/*  information please refer to the GUIX Studio user's guide, or visit our web */
/*  site at www.expresslogic.com.                                              */
/*                                                                             */
/*  GUIX Studio Revision 5.4.0.0                                               */
/*  Date (dd.mm.yyyy):  8. 6.2018   Time (hh:mm): 17:30                        */
/*******************************************************************************/


#ifndef _WEATHER_GNU_MAIN_DISPLAY_RESOURCES_H_
#define _WEATHER_GNU_MAIN_DISPLAY_RESOURCES_H_

#include "gx_api.h"

/* Display and theme definitions                                               */

#define MAIN_DISPLAY 0
#define MAIN_DISPLAY_COLOR_FORMAT GX_COLOR_FORMAT_565RGB
#define MAIN_DISPLAY_X_RESOLUTION 256
#define MAIN_DISPLAY_Y_RESOLUTION 320
#define MAIN_DISPLAY_THEME_1 0
#define MAIN_DISPLAY_THEME_TABLE_SIZE 1

/* Language definitions                                                        */

#define LANGUAGE_ENGLISH 0
#define MAIN_DISPLAY_LANGUAGE_TABLE_SIZE 1

/* Color ID definitions                                                        */

#define GX_COLOR_ID_CANVAS 0
#define GX_COLOR_ID_WIDGET_FILL 1
#define GX_COLOR_ID_WINDOW_FILL 2
#define GX_COLOR_ID_DEFAULT_BORDER 3
#define GX_COLOR_ID_WINDOW_BORDER 4
#define GX_COLOR_ID_TEXT 5
#define GX_COLOR_ID_SELECTED_TEXT 6
#define GX_COLOR_ID_SELECTED_FILL 7
#define GX_COLOR_ID_SHADOW 8
#define GX_COLOR_ID_SHINE 9
#define GX_COLOR_ID_BTN_BORDER 10
#define GX_COLOR_ID_BTN_UPPER 11
#define GX_COLOR_ID_BTN_LOWER 12
#define GX_COLOR_ID_BTN_TEXT 13
#define GX_COLOR_ID_SCROLL_FILL 14
#define GX_COLOR_ID_SCROLL_BUTTON 15
#define GX_COLOR_ID_TEXT_INPUT_TEXT 16
#define GX_COLOR_ID_TEXT_INPUT_FILL 17
#define GX_COLOR_ID_SLIDER_TICK 18
#define GX_COLOR_ID_SLIDER_GROOVE_TOP 19
#define GX_COLOR_ID_SLIDER_GROOVE_BOTTOM 20
#define GX_COLOR_ID_SLIDER_NEEDLE_OUTLINE 21
#define GX_COLOR_ID_SLIDER_NEEDLE_FILL 22
#define GX_COLOR_ID_SLIDER_NEEDLE_LINE1 23
#define GX_COLOR_ID_SLIDER_NEEDLE_LINE2 24
#define MAIN_DISPLAY_COLOR_TABLE_SIZE 25

/* Font ID definitions                                                         */

#define GX_FONT_ID_SYSTEM 0
#define GX_FONT_ID_BUTTON 1
#define GX_FONT_ID_PROMPT 2
#define GX_FONT_ID_TEXT_INPUT 3
#define GX_FONT_ID_MEDIUM 4
#define GX_FONT_ID_LARGE 5
#define GX_FONT_ID_SMALL 6
#define MAIN_DISPLAY_FONT_TABLE_SIZE 7

/* Pixelmap ID definitions                                                     */

#define GX_PIXELMAP_ID_RADIO_ON 1
#define GX_PIXELMAP_ID_RADIO_OFF 2
#define GX_PIXELMAP_ID_CHECKBOX_ON 3
#define GX_PIXELMAP_ID_CHECKBOX_OFF 4
#define GX_PIXELMAP_ID_BUTTON_PLUS_PRESSED 5
#define GX_PIXELMAP_ID_BUTTON_MINUS 6
#define GX_PIXELMAP_ID_BUTTON_PLUS 7
#define GX_PIXELMAP_ID_ICON_SUNNY 8
#define GX_PIXELMAP_ID_ICON_CLOUDY 9
#define GX_PIXELMAP_ID_ICON_RAINY 10
#define GX_PIXELMAP_ID_SYMBOL_DEG 11
#define GX_PIXELMAP_ID_SYMBOL_DEG_F 12
#define GX_PIXELMAP_ID_BUTTON_MINUS_PRESSED 13
#define GX_PIXELMAP_ID_BOTTOM_BUTTON_TRANS_PRESSED 14
#define GX_PIXELMAP_ID_BOTTOM_BUTTON_TRANS 15
#define GX_PIXELMAP_ID_ANIME_SUN_SHINING 16
#define GX_PIXELMAP_ID_ANIME_RAINING_2 17
#define GX_PIXELMAP_ID_ANIME_RAINING_1 18
#define GX_PIXELMAP_ID_ANIME_SUN_ONCLOUD 19
#define GX_PIXELMAP_ID_BOX_THERMOSTAT 20
#define GX_PIXELMAP_ID_BG_THERMOSTAT 21
#define GX_PIXELMAP_ID_ANIME_CLOUD 22
#define GX_PIXELMAP_ID_BG_PARTLYCLOUDY 23
#define GX_PIXELMAP_ID_BG_RAINY 24
#define GX_PIXELMAP_ID_BG_SUNNY 25
#define GX_PIXELMAP_ID_SPLASH_SCREEN 26
#define MAIN_DISPLAY_PIXELMAP_TABLE_SIZE 27

/* String Ids                                                                  */

#define GX_STRING_ID_STRING_THERMOSTAT 1
#define GX_STRING_ID_STRING_TARGET_TEMP 2
#define GX_STRING_ID_STRING_FORECAST_TEMP 3
#define GX_STRING_ID_STRING_SUN 4
#define GX_STRING_ID_STRING_MON 5
#define GX_STRING_ID_STRING_TUE 6
#define GX_STRING_ID_STRING_WED 7
#define GX_STRING_ID_STRING_THU 8
#define GX_STRING_ID_STRING_FRI 9
#define GX_STRING_ID_STRING_SAT 10
#define GX_STRING_ID_STRING_TEMP_RANGE 11
#define GX_STRING_ID_STRING_DATE 12
#define GX_STRING_ID_STRING_TIME 13
#define GX_STRING_ID_STRING_FORECAST_DAY 14
#define GX_STRING_ID_STRING_FORECAST_HUMIDITY 15
#define GX_STRING_ID_STRING_1 16
#define GX_STRING_ID_STRING_2 17
#define GX_STRING_ID_STRING_3 18
#define GX_STRING_ID_STRING_4 19
#define GX_STRING_ID_STRING_5 20
#define GX_STRING_ID_STRING_6 21
#define MAIN_DISPLAY_STRING_TABLE_SIZE 22

#endif                                       /* sentry                         */
